- name: "Create proxy_net if it does not exist"
  become: True
  docker_network:
    name: proxy_net

- include: create_volumes.yml
  become: True
  tags:
    - jenkins_volumes_setup
    - jenkins_setup

- include: setup.yml
  become: True
  tags: jenkins_setup

- include: backup.yml
  become: True
  tags: jenkins_all_backup


- include: restore.yml
  become: True
  tags: jenkins_all_restore

- name: "Allow docker containers to communicate with the outside"
  become: True
  tags:
   - jenkins_deploy
   - jenkins_restore
  command: iptables -t nat -A POSTROUTING -s 173.16.0.0/12 ! -d 172.16.0.0/12 -j MASQUERADE

- name: "get docker path"
  tags: dockerpath
  command: which docker
  register: docker_path

- name: "Start jenkins container w/ ssl"
  when: SSL == True
  become: True
  tags:
    - jenkins_deploy
    - jenkins_restore
  docker_container:
    name: jenkins
    image: forgottenbeast/jenkins:latest
    state: started
    env:
     VIRTUAL_HOST: "{{ jenkins_domain_name }}"
     VIRTUAL_PROTO: http
     VIRTUAL_PORT: 8080
     LETSENCRYPT_HOST: "{{ jenkins_letsencrypt_domain_name }}"
     LETSENCRYPT_EMAIL: "{{ jenkins_letsencrypt_mail }}"
     LETSENCRYPT_TEST: "{{ jenkins_letsencrypt_testmode }}"

    networks:
      - proxy_net
    volumes:
      - "{{ JENKINS_VOLUME }}:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{docker_path.stdout}}:{{docker_path.stdout}}"

- name: "Start jenkins container w/o SSL"
  become: True
  when: SSL == False
  tags:
    - jenkins_deploy
    - jenkins_restore
  docker_container:
    name: jenkins
    image: forgottenbeast/jenkins:latest
    state: started
    env:
     VIRTUAL_HOST: "{{ jenkins_domain_name }}"
     VIRTUAL_PROTO: http
     VIRTUAL_PORT: 8080
    networks:
      - proxy_net
    volumes:
      - "{{ JENKINS_VOLUME }}:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{docker_path.stdout}}:{{docker_path.stdout}}"

