- name: "Update local jenkins clean image"
  docker_image:
    name: redmine/jenkins:latest
    state: present
    force: True
    pull: True

- name: "Start temporary clean redmine service to copy files"
  docker_container:
    name: tmp_jenkins
    image: jenkins/jenkins:latest
    state: started
    volumes:
      - "{{ JENKINS_VOLUME }}:/jenkins_files"

- name: "Copy clean files to docker volumes"
  shell: |
    docker exec tmp_redmine bash -c "cp -a /var/jenkins_home/. /jenkins_files;"

- name: "Stop temporary services"
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - tmp_jenkins
